import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'al';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.login': 'Login',
    'header.signup': 'Sign Up',
    'header.logout': 'Logout',
    'header.profile': 'Profile',
    'header.about': 'About Us',
    
    // Hero
    'hero.title': 'Fitness Practica',
    'hero.subtitle.1': 'Transform your body, focus your mind, reach the peaks.',
    'hero.subtitle.2': "Don't dream of transformation. Make it reality.",
    'hero.subtitle.3': 'Shape is not the end — it\'s your new beginning.',
    'hero.subtitle.4': 'Strength is within you. We help you unleash it.',
    'hero.subtitle.5': 'The gym doesn\'t just change the body. It changes life.',
    'hero.subtitle.6': 'Build the body, feed the mind, unleash the potential.',
    'hero.subtitle.7': 'Work hard, think clearly, achieve everything.',
    'hero.subtitle.8': 'Transform yourself – physically, mentally, completely.',
    'hero.subtitle.9': 'Build the body, clarify the mind, achieve goals.',
    'hero.button': 'Start Your Journey',
    
    // Sections
    'section.plans.title': 'Choose Your Plan',
    'section.plans.subtitle': 'Find the perfect fit for your fitness journey',
    'section.programs.title': 'Training Programs',
    'section.programs.subtitle': 'Specialized programs designed for your goals',
    'section.about.title': 'Your Fitness',
    'section.about.title2': 'Transformation',
    'section.locations.title': 'Our Locations',
    'section.locations.subtitle': 'Find us at one of our convenient locations',
    'section.livestreams.title': 'Live Streams',
    'section.livestreams.subtitle': 'Join our live training sessions from anywhere',
    
    // Footer
    'footer.tagline': 'Transform your life through fitness',
    'footer.contact': 'Contact Us',
    'footer.hours': 'Hours',
    'footer.hours.weekdays': 'Monday - Saturday: 06:00 - 23:00',
    'footer.hours.weekend': 'Sunday: 10:00 - 20:00',
    'footer.copyright': '© 2025 Fitness Practica. All rights reserved.',
    'footer.socials': 'Socials',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.empty': 'Your cart is empty',
    'checkout.emptyMessage': 'Add some programs to your cart to get started!',
    'checkout.program': 'Program',
    'checkout.category': 'Category',
    'checkout.remove': 'Remove',
    'checkout.total': 'Total',
    'checkout.programs': 'programs',
    'checkout.completeOrder': 'Complete Order',
    'checkout.backToPrograms': 'Back to Programs',
    
    // Buttons
    'button.learnMore': 'Learn More',
    'button.browsePrograms': 'Browse Programs',
    'button.loginToPurchase': 'Log in to purchase',
    'button.continue': 'Continue',
    'button.addToCart': 'Add to Cart',
    
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.emailPlaceholder': 'Enter your email',
    'login.passwordPlaceholder': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up',
    'login.failed': 'Login failed. Please try again.',
    
    // Signup
    'signup.title': 'Create Account',
    'signup.subtitle': 'Join us and start your fitness journey',
    'signup.name': 'Full Name',
    'signup.email': 'Email',
    'signup.password': 'Password',
    'signup.confirmPassword': 'Confirm Password',
    'signup.phone': 'Phone',
    'signup.namePlaceholder': 'Enter your full name',
    'signup.emailPlaceholder': 'Enter your email',
    'signup.passwordPlaceholder': 'Create a password',
    'signup.confirmPasswordPlaceholder': 'Confirm your password',
    'signup.phonePlaceholder': 'Enter your phone number',
    'signup.createAccount': 'Sign Up',
    'signup.creating': 'Creating account...',
    'signup.hasAccount': 'Already have an account?',
    'signup.signIn': 'Sign in',
    'signup.passwordsNotMatch': 'Passwords do not match',
    'signup.passwordTooShort': 'Password must be at least 6 characters',
    'signup.phoneRequired': 'Phone number is required',
    'signup.failed': 'Signup failed. Please try again.',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your account and view your purchased programs',
    'profile.information': 'Profile Information',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.role': 'Role',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.myPrograms': 'My Programs',
    'profile.noPrograms': 'No programs purchased yet',
    'profile.programStatus': 'Status',
    'profile.programStatusActive': 'Active',
    'profile.programStatusFinished': 'Finished',
    'profile.programStatusUpcoming': 'Not Available Yet',
    'profile.programDescription': 'Description',
    'profile.programNoDescription': 'No description available',
    'profile.videoStatus': 'Status',
    'profile.videoNotStarted': 'Not Started',
    'profile.videoInProgress': 'In Progress',
    'profile.videoCompleted': 'Completed',
    'profile.videoLocked': 'Locked - Complete previous video',
    'profile.memberSince': 'Member Since',
    'profile.startProgram': 'Start Program',
    
    // Checkout
    'checkout.proceedToPayment': 'Proceed to Payment',
    'checkout.processing': 'Processing...',
    'checkout.paymentSuccess': 'Payment successful! Redirecting to profile...',
    'checkout.paymentFailed': 'Payment failed or was canceled. Please try again.',
    'checkout.noValidPrograms': 'No valid programs in cart',
    'checkout.failedToCreateSession': 'Failed to create checkout session',
    'checkout.failedToProcess': 'Failed to process payment',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.loading': 'Loading dashboard...',
    'admin.accessDenied': 'Access denied. Admin privileges required.',
    'admin.stats': 'Statistics',
    'admin.users': 'Users',
    'admin.transactions': 'Transactions',
    'admin.programs': 'Programs',
    'admin.addUser': 'Add User',
    'admin.addProgram': 'Add Program',
    'admin.totalUsers': 'Total Users',
    'admin.totalTransactions': 'Total Transactions',
    'admin.totalRevenue': 'Total Revenue',
    'admin.recentTransactions': 'Recent Transactions (30 days)',
    'admin.noUsers': 'No users found',
    'admin.noTransactions': 'No transactions found',
    'admin.noPrograms': 'No programs found',
    'admin.id': 'ID',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.phone': 'Phone',
    'admin.role': 'Role',
    'admin.payments': 'Payments',
    'admin.created': 'Created',
    'admin.userName': 'User Name',
    'admin.userEmail': 'User Email',
    'admin.itemName': 'Item Name',
    'admin.itemType': 'Item Type',
    'admin.amount': 'Amount',
    'admin.status': 'Status',
    'admin.date': 'Date',
    'admin.category': 'Category',
    'admin.description': 'Description',
    'admin.price': 'Price',
    'admin.startDate': 'Start Date',
    'admin.endDate': 'End Date',
    'admin.imageUrl': 'Image URL',
    'admin.actions': 'Actions',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.editProgram': 'Edit Program',
    'admin.deleteProgram': 'Delete Program',
    'admin.viewImage': 'View Image',
    'admin.free': 'Free',
    'admin.na': 'N/A',
    'admin.createUserTitle': 'Create New User',
    'admin.nameRequired': 'Name *',
    'admin.emailRequired': 'Email *',
    'admin.passwordRequired': 'Password *',
    'admin.creating': 'Creating...',
    'admin.createUser': 'Create User',
    'admin.userCreated': 'User created successfully!',
    'admin.failedToCreateUser': 'Failed to create user',
    'admin.emailPasswordNameRequired': 'Email, password, and name are required',
    'admin.createProgramTitle': 'Create New Training Program',
    'admin.editProgramTitle': 'Edit Training Program',
    'admin.programName': 'Program Name',
    'admin.programCategory': 'Category',
    'admin.programDescription': 'Description',
    'admin.programImage': 'Program Image',
    'admin.programPrice': 'Price (ALL)',
    'admin.programStartDate': 'Start Date',
    'admin.programEndDate': 'End Date',
    'admin.programNamePlaceholder': 'e.g., Fat Burn Program',
    'admin.programCategoryPlaceholder': 'e.g., Weight Loss, Muscle Growth',
    'admin.programDescriptionPlaceholder': 'Program description...',
    'admin.programPricePlaceholder': '49.99',
    'admin.next': 'Next',
    'admin.back': 'Back',
    'admin.uploadVideo': 'Upload Video',
    'admin.selectExistingVideo': 'Select Existing Video',
    'admin.nameCategoryRequired': 'Name and category are required',
    'admin.programCreated': 'Program created successfully!',
    'admin.programUpdated': 'Program updated successfully!',
    'admin.programDeleted': 'Program deleted successfully!',
    'admin.failedToCreateProgram': 'Failed to create program',
    'admin.failedToUpdateProgram': 'Failed to update program',
    'admin.failedToDeleteProgram': 'Failed to delete program',
    'admin.failedToLoadProgram': 'Failed to load program',
    'admin.failedToLoadDetails': 'Failed to load program details',
    'admin.noProgramSelected': 'No program selected for editing',
    'admin.failedToUploadImage': 'Failed to upload image',
    'admin.programCreatedVideoFailed': 'Program created but video attachment failed. You can attach it later.',
    'admin.deleteConfirm': 'Are you sure you want to delete this program? This will also delete all associated videos. This action cannot be undone.',
    'admin.updating': 'Updating...',
    'admin.updateProgram': 'Update Program',
    'admin.videoUpdated': 'Video updated successfully with new exercises!',
    'admin.videoProcessedUpdateFailed': 'Video processed but update failed. Please try updating the program.',
    'admin.processingFinishedUnexpected': 'Processing finished but server returned unexpected JSON.',
    'admin.errorConnecting': 'Error connecting to server.',
    'admin.uploadVideoOrSelect': 'Please upload a video or select an existing video first!',
    'admin.markExercise': 'Please mark at least one exercise first!',
    'admin.addExerciseOrOverlay': 'Please add at least one exercise or overlay.',
    'admin.authTokenNotFound': 'Authentication token not found. Please log in again.',
    'admin.switchLanguage': 'Switch to Albanian',
    'admin.switchToEnglish': 'Kalo në Anglisht',
    'admin.cart': 'Cart',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.failed': 'Failed',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.view': 'View',
    'common.details': 'Details',
    'common.settings': 'Settings',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.select': 'Select',
    'common.choose': 'Choose',
    'common.remove': 'Remove',
    'common.clear': 'Clear',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.processing': 'Processing...',
    'common.processingVideo': 'Processing...',
    'common.processExportVideo': 'Process & Export Video',
    // Extras for homepage/profile
    'common.free': 'Free',
    'index.viewHours': 'View Hours',
    'index.noPrograms': 'No training programs available at the moment.',
    'index.starts': 'Starts',
    'index.ends': 'Ends',
    'index.about.p1': "At Fitness Practica, we believe fitness is more than just working out—it's a lifestyle. Our state-of-the-art facilities are equipped with the latest training equipment, expert trainers, and a supportive community to help you reach your peak performance.",
    'index.about.p2': 'Whether you\'re a beginner starting your fitness journey or an experienced athlete pushing your limits, we provide personalized training programs, group classes, and nutritional guidance tailored to your unique goals.',
    'profile.purchased': 'Purchased',
    'profile.expires': 'Expires',
    'profile.openMedia': 'Open attached media',
    'profile.viewDetails': 'View program details',
    'profile.unknownProgram': 'Unknown Program',
    'profile.programDates': 'Program Dates',
    'profile.noVideos': 'No videos attached to this program yet.',
    'profile.continue': 'Continue',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    'profile.currentPasswordPlaceholder': 'Enter current password',
    'profile.newPasswordPlaceholder': 'Enter new password',
    'profile.confirmNewPasswordPlaceholder': 'Confirm new password',
    'profile.passwordUpdated': 'Password updated successfully!',
    'profile.passwordUpdateFailed': 'Failed to update password',
    'profile.passwordsNotMatch': 'New passwords do not match',
    'profile.passwordTooShort': 'Password must be at least 6 characters',
    'profile.currentPasswordRequired': 'Current password is required',
    'profile.changeEmail': 'Change Email',
    'profile.newEmail': 'New Email',
    'profile.newEmailPlaceholder': 'Enter new email',
    'profile.emailUpdated': 'Email updated successfully!',
    'profile.emailUpdateFailed': 'Failed to update email',
    'profile.emailAlreadyExists': 'Email already in use',
    'profile.invalidEmail': 'Invalid email format',
    
    // About Us
    'about.title': 'About Us',
    'about.subtitle': 'Your trusted partner in fitness and wellness',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'At Fitness Practica, we are dedicated to helping individuals achieve their fitness goals through personalized training programs, expert guidance, and a supportive community. We believe that everyone deserves access to quality fitness resources that can transform their lives.',
    'about.values.title': 'Our Values',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.description': 'We strive for excellence in every program we offer, ensuring the highest quality training experiences.',
    'about.values.community.title': 'Community',
    'about.values.community.description': 'We build a supportive community where members can share their journey and motivate each other.',
    'about.values.dedication.title': 'Dedication',
    'about.values.dedication.description': 'We are committed to your success and dedicated to helping you reach your fitness goals.',
    'about.values.quality.title': 'Quality',
    'about.values.quality.description': 'Every program is carefully crafted by fitness experts to ensure the best results.',
    'about.values.progress.title': 'Progress',
    'about.values.progress.description': 'We track and celebrate your progress, helping you stay motivated and achieve continuous improvement.',
    'about.story.title': 'Our Story',
    'about.story.paragraph1': 'Fitness Practica was founded with a simple yet powerful vision: to make professional fitness training accessible to everyone. We understand that each person\'s fitness journey is unique, and we\'re here to provide the tools, guidance, and support needed to succeed.',
    'about.story.paragraph2': 'Our team of experienced trainers and fitness experts work tirelessly to create comprehensive programs that cater to various fitness levels and goals. Whether you\'re looking to lose weight, build muscle, improve flexibility, or enhance your overall health, we have a program designed for you.',
    'about.story.paragraph3': 'Join thousands of satisfied members who have transformed their lives through our programs. Your fitness journey starts here, and we\'re excited to be part of it.',
    'about.box1.title': 'Our Commitment',
    'about.box1.description': '<p style="margin-bottom: 1rem;">🔹 <strong>Position:</strong> Fitness Instructor, Aerobics, Pilates, Tabata Insanity</p><p style="margin-bottom: 1rem;">🔹 <strong>Experience:</strong> Over 25 years in the field of physical activity</p><p style="margin-bottom: 0.5rem;">🔹 <strong>Specializations:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Functional fitness</li><li style="margin-bottom: 0.25rem;">▪ Aerobic training, Pilates, Tabata Insanity, Full Body workout</li><li style="margin-bottom: 0.25rem;">▪ Physical conditioning for all ages</li><li style="margin-bottom: 0.25rem;">▪ Athletic and physical preparation</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Training Style:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Structured, clear and motivating</li><li style="margin-bottom: 0.25rem;">▪ Adapted for all levels – from beginners to advanced</li><li style="margin-bottom: 0.25rem;">▪ Focus on correct technique and gradual progress</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Benefits of working with him:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Deep and proven experience of 25 years</li><li style="margin-bottom: 0.25rem;">▪ Positive approach and inspiring energy</li><li style="margin-bottom: 0.25rem;">▪ Individual attention for each client</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>His Mission:</strong></p><p style="padding-left: 1.5rem; margin-bottom: 1rem;">To help every individual reach their maximum potential – physically and mentally.</p><p style="margin-bottom: 0.5rem;">🔹 <strong>Motto:</strong></p><p style="padding-left: 1.5rem; margin-bottom: 0;">"Discipline builds the body, dedication strengthens character."</p>',
    'about.box2.title': 'Your Success',
    'about.box2.description': '<p style="margin-bottom: 1rem;">🔹 <strong>Position:</strong> Fitness Instructor & Pilates</p><p style="margin-bottom: 1rem;">🔹 <strong>Experience:</strong> 8 years in the field of personal and group training</p><p style="margin-bottom: 0.5rem;">🔹 <strong>Specializations:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Functional fitness and strength</li><li style="margin-bottom: 0.25rem;">▪ Pilates for stability, flexibility and balance</li><li style="margin-bottom: 0.25rem;">▪ Training for toning and physical performance</li><li style="margin-bottom: 0.25rem;">▪ Athletic and physical preparation</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Training Style:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Dynamic, contemporary and adapted to individual needs</li><li style="margin-bottom: 0.25rem;">▪ Combines modern Pilates techniques with basic fitness principles</li><li style="margin-bottom: 0.25rem;">▪ Focus on mind-body connection and long-term progress</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Benefits of working with him:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Professional and friendly approach</li><li style="margin-bottom: 0.25rem;">▪ Organized and effective sessions</li><li style="margin-bottom: 0.25rem;">▪ Continuous support for motivation and improvement</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>His Mission:</strong></p><p style="padding-left: 1.5rem; margin-bottom: 1rem;">To help every client feel stronger, more stable and more confident in their own body.</p><p style="margin-bottom: 0.5rem;">🔹 <strong>Motto:</strong></p><p style="padding-left: 1.5rem; margin-bottom: 0;">"The body is your tool – learn to use it with control and awareness."</p>',
  },
  al: {
    // Header
    'header.login': 'Hyr',
    'header.signup': 'Regjistrohu',
    'header.logout': 'Dil',
    'header.profile': 'Profili',
    'header.about': 'Rreth Nesh',
    
    // Hero
    'hero.title': 'Fitness Practica',
    'hero.subtitle.1': 'Transformo trupin, fokuso mendjen, arri majat.',
    'hero.subtitle.2': 'Mos ëndërro transformimin. Bëje realitet.',
    'hero.subtitle.3': 'Forma nuk është fundi — është fillimi yt i ri.',
    'hero.subtitle.4': 'Fuqia është brenda teje. Ne ndihmojmë ta nxjerrësh.',
    'hero.subtitle.5': 'Palestra nuk ndryshon vetëm trupin. Ndryshon jetën.',
    'hero.subtitle.6': 'Ndërto formën, ushqe mendjen, çliro potencialin.',
    'hero.subtitle.7': 'Puno fort, mendo qartë, arrij gjithçka.',
    'hero.subtitle.8': 'Transformo veten – fizikisht, mendërisht, plotësisht.',
    'hero.subtitle.9': 'Rrit trupin, qartëso mendjen, arri qëllimet.',
    'hero.button': 'Fillo Udhëtimin Tënd',
    
    // Sections
    'section.plans.title': 'Zgjidh Planin Tënd',
    'section.plans.subtitle': 'Gjej përshtatjen e përsosur për udhëtimin tënd të fitnesit',
    'section.programs.title': 'Programe Trajnimi',
    'section.programs.subtitle': 'Programe të specializuara të dizajnuara për qëllimet e tua',
    'section.about.title': 'Transformimi',
    'section.about.title2': 'i Fitnesit Tënd',
    'section.locations.title': 'Lokacionet Tona',
    'section.locations.subtitle': 'Na gjej në një nga lokacionet tona të përshtatshme',
    'section.livestreams.title': 'Transmetime Live',
    'section.livestreams.subtitle': 'Bashkohu me seancat tona të trajnimit live nga kudo',
    
    // Footer
    'footer.tagline': 'Transformo jetën përmes fitnesit',
    'footer.contact': 'Kontakto',
    'footer.hours': 'Orët',
    'footer.hours.weekdays': 'E Hënë - E Shtunë: 06:00 - 23:00',
    'footer.hours.weekend': 'E Dielë: 10:00 - 20:00',
    'footer.copyright': '© 2025 Fitness Practica. Të gjitha të drejtat e rezervuara.',
    'footer.socials': 'Rrjetet Sociale',
    
    // Checkout
    'checkout.title': 'Blerje',
    'checkout.empty': 'Shporta juaj është e zbrazët',
    'checkout.emptyMessage': 'Shtoni disa programe në shportën tuaj për të filluar!',
    'checkout.program': 'Programi',
    'checkout.category': 'Kategoria',
    'checkout.remove': 'Hiq',
    'checkout.total': 'Totali',
    'checkout.programs': 'programe',
    'checkout.completeOrder': 'Përfundo Porosinë',
    'checkout.backToPrograms': 'Kthehu te Programet',
    
    // Buttons
    'button.learnMore': 'Më Shumë',
    'button.browsePrograms': 'Shfleto Programet',
    'button.loginToPurchase': 'Hyr për të blerë',
    'button.continue': 'Vazhdo',
    'button.addToCart': 'Shto në Shportë',
    
    // Login
    'login.title': 'Mirë Se Vini',
    'login.subtitle': 'Hyni në llogarinë tuaj',
    'login.email': 'Email',
    'login.password': 'Fjalëkalimi',
    'login.emailPlaceholder': 'Shkruani email-in tuaj',
    'login.passwordPlaceholder': 'Shkruani fjalëkalimin tuaj',
    'login.signIn': 'Hyr',
    'login.signingIn': 'Duke hyrë...',
    'login.noAccount': 'Nuk keni llogari?',
    'login.signUp': 'Regjistrohu',
    'login.failed': 'Hyrja dështoi. Ju lutemi provoni përsëri.',
    
    // Signup
    'signup.title': 'Krijo Llogari',
    'signup.subtitle': 'Bashkohuni me ne dhe filloni udhëtimin tuaj të fitnesit',
    'signup.name': 'Emri i Plotë',
    'signup.email': 'Email',
    'signup.password': 'Fjalëkalimi',
    'signup.confirmPassword': 'Konfirmo Fjalëkalimin',
    'signup.phone': 'Telefoni',
    'signup.namePlaceholder': 'Shkruani emrin tuaj të plotë',
    'signup.emailPlaceholder': 'Shkruani email-in tuaj',
    'signup.passwordPlaceholder': 'Krijoni një fjalëkalim',
    'signup.confirmPasswordPlaceholder': 'Konfirmoni fjalëkalimin tuaj',
    'signup.phonePlaceholder': 'Shkruani numrin e telefonit',
    'signup.createAccount': 'Regjistrohu',
    'signup.creating': 'Duke krijuar llogarinë...',
    'signup.hasAccount': 'Keni tashmë një llogari?',
    'signup.signIn': 'Hyr',
    'signup.passwordsNotMatch': 'Fjalëkalimet nuk përputhen',
    'signup.passwordTooShort': 'Fjalëkalimi duhet të jetë të paktën 6 karaktere',
    'signup.phoneRequired': 'Numri i telefonit është i detyrueshëm',
    'signup.failed': 'Regjistrimi dështoi. Ju lutemi provoni përsëri.',
    
    // Profile
    'profile.title': 'Profili Im',
    'profile.subtitle': 'Menaxhoni llogarinë tuaj dhe shikoni programet e blera',
    'profile.information': 'Informacioni i Profilit',
    'profile.name': 'Emri',
    'profile.email': 'Email',
    'profile.phone': 'Telefoni',
    'profile.role': 'Roli',
    'profile.save': 'Ruaj',
    'profile.cancel': 'Anulo',
    'profile.myPrograms': 'Programet e Mia',
    'profile.noPrograms': 'Nuk keni blerë programe ende',
    'profile.programStatus': 'Statusi',
    'profile.programStatusActive': 'Aktiv',
    'profile.programStatusFinished': 'Përfunduar',
    'profile.programStatusUpcoming': 'Ende Nuk Është i Disponueshëm',
    'profile.programDescription': 'Përshkrimi',
    'profile.programNoDescription': 'Nuk ka përshkrim të disponueshëm',
    'profile.videoStatus': 'Statusi',
    'profile.videoNotStarted': 'Nuk Është Filluar',
    'profile.videoInProgress': 'Në Progres',
    'profile.videoCompleted': 'Përfunduar',
    'profile.videoLocked': 'E Kyçur - Përfundoni videon e mëparshme',
    'profile.memberSince': 'Anëtar Që',
    'profile.startProgram': 'Fillo Programin',
    
    // Checkout
    'checkout.proceedToPayment': 'Vazhdo te Pagesa',
    'checkout.processing': 'Duke përpunuar...',
    'checkout.paymentSuccess': 'Pagesa u krye me sukses! Po ridrejtohet te profili...',
    'checkout.paymentFailed': 'Pagesa dështoi ose u anulua. Ju lutemi provoni përsëri.',
    'checkout.noValidPrograms': 'Nuk ka programe të vlefshme në shportë',
    'checkout.failedToCreateSession': 'Dështoi krijimi i sesionit të blerjes',
    'checkout.failedToProcess': 'Dështoi përpunimi i pagesës',
    
    // Admin Dashboard
    'admin.dashboard': 'Paneli i Administratorit',
    'admin.loading': 'Duke ngarkuar panelin...',
    'admin.accessDenied': 'Qasja u refuzua. Kërkohen privilegje administratori.',
    'admin.stats': 'Statistikat',
    'admin.users': 'Përdoruesit',
    'admin.transactions': 'Transaksionet',
    'admin.programs': 'Programet',
    'admin.addUser': 'Shto Përdorues',
    'admin.addProgram': 'Shto Program',
    'admin.totalUsers': 'Totali i Përdoruesve',
    'admin.totalTransactions': 'Totali i Transaksioneve',
    'admin.totalRevenue': 'Të Ardhurat Totale',
    'admin.recentTransactions': 'Transaksionet e Fundit (30 ditë)',
    'admin.noUsers': 'Nuk u gjetën përdorues',
    'admin.noTransactions': 'Nuk u gjetën transaksione',
    'admin.noPrograms': 'Nuk u gjetën programe',
    'admin.id': 'ID',
    'admin.name': 'Emri',
    'admin.email': 'Email',
    'admin.phone': 'Telefoni',
    'admin.role': 'Roli',
    'admin.payments': 'Pagesat',
    'admin.created': 'Krijuar',
    'admin.userName': 'Emri i Përdoruesit',
    'admin.userEmail': 'Email i Përdoruesit',
    'admin.itemName': 'Emri i Artikullit',
    'admin.itemType': 'Lloji i Artikullit',
    'admin.amount': 'Shuma',
    'admin.status': 'Statusi',
    'admin.date': 'Data',
    'admin.category': 'Kategoria',
    'admin.description': 'Përshkrimi',
    'admin.price': 'Çmimi',
    'admin.startDate': 'Data e Fillimit',
    'admin.endDate': 'Data e Mbarimit',
    'admin.imageUrl': 'URL e Imazhit',
    'admin.actions': 'Veprimet',
    'admin.edit': 'Ndrysho',
    'admin.delete': 'Fshi',
    'admin.editProgram': 'Ndrysho Programin',
    'admin.deleteProgram': 'Fshi Programin',
    'admin.viewImage': 'Shiko Imazhin',
    'admin.free': 'Falas',
    'admin.na': 'N/A',
    'admin.createUserTitle': 'Krijo Përdorues të Ri',
    'admin.nameRequired': 'Emri *',
    'admin.emailRequired': 'Email *',
    'admin.passwordRequired': 'Fjalëkalimi *',
    'admin.creating': 'Duke krijuar...',
    'admin.createUser': 'Krijo Përdorues',
    'admin.userCreated': 'Përdoruesi u krijua me sukses!',
    'admin.failedToCreateUser': 'Dështoi krijimi i përdoruesit',
    'admin.emailPasswordNameRequired': 'Email, fjalëkalimi dhe emri janë të detyrueshëm',
    'admin.createProgram': 'Krijo Program Trajnimi të Ri',
    'admin.createProgramTitle': 'Krijo Program Trajnimi të Ri',
    'admin.editProgramTitle': 'Ndrysho Program Trajnimi',
    'admin.programName': 'Emri i Programit',
    'admin.programCategory': 'Kategoria',
    'admin.programDescription': 'Përshkrimi',
    'admin.programImage': 'Imazhi i Programit',
    'admin.programPrice': 'Çmimi (ALL)',
    'admin.programStartDate': 'Data e Fillimit',
    'admin.programEndDate': 'Data e Mbarimit',
    'admin.programNamePlaceholder': 'p.sh., Program Djegie Yndyri',
    'admin.programCategoryPlaceholder': 'p.sh., Humbje Peshe, Rritje Muskujsh',
    'admin.programDescriptionPlaceholder': 'Përshkrimi i programit...',
    'admin.programPricePlaceholder': '49.99',
    'admin.next': 'Tjetra',
    'admin.back': 'Mbrapa',
    'admin.uploadVideo': 'Ngarko Video',
    'admin.selectExistingVideo': 'Zgjidh Video Ekzistuese',
    'admin.nameCategoryRequired': 'Emri dhe kategoria janë të detyrueshëm',
    'admin.programCreated': 'Programi u krijua me sukses!',
    'admin.programUpdated': 'Programi u përditësua me sukses!',
    'admin.programDeleted': 'Programi u fshi me sukses!',
    'admin.failedToCreateProgram': 'Dështoi krijimi i programit',
    'admin.failedToUpdateProgram': 'Dështoi përditësimi i programit',
    'admin.failedToDeleteProgram': 'Dështoi fshirja e programit',
    'admin.failedToLoadProgram': 'Dështoi ngarkimi i programit',
    'admin.failedToLoadDetails': 'Dështoi ngarkimi i detajeve të programit',
    'admin.noProgramSelected': 'Nuk është zgjedhur program për ndryshim',
    'admin.failedToUploadImage': 'Dështoi ngarkimi i imazhit',
    'admin.programCreatedVideoFailed': 'Programi u krijua por lidhja e videos dështoi. Mund ta lidhni më vonë.',
    'admin.deleteConfirm': 'Jeni të sigurt që dëshironi të fshini këtë program? Kjo do të fshijë edhe të gjitha videot e lidhura. Ky veprim nuk mund të zhbëhet.',
    'admin.updating': 'Duke përditësuar...',
    'admin.updateProgram': 'Përditëso Programin',
    'admin.videoUpdated': 'Videoja u përditësua me sukses me ushtrime të reja!',
    'admin.videoProcessedUpdateFailed': 'Videoja u përpunua por përditësimi dështoi. Ju lutemi provoni të përditësoni programin.',
    'admin.processingFinishedUnexpected': 'Përpunimi përfundoi por serveri ktheu JSON të papritur.',
    'admin.errorConnecting': 'Gabim në lidhje me serverin.',
    'admin.uploadVideoOrSelect': 'Ju lutemi ngarkoni një video ose zgjidhni një video ekzistuese!',
    'admin.markExercise': 'Ju lutemi shënoni të paktën një ushtrim fillimisht!',
    'admin.addExerciseOrOverlay': 'Ju lutemi shtoni të paktën një ushtrim ose mbivendosje.',
    'admin.authTokenNotFound': 'Tokeni i autentifikimit nuk u gjet. Ju lutemi hyni përsëri.',
    'admin.switchLanguage': 'Kalo në Shqip',
    'admin.switchToEnglish': 'Switch to English',
    'admin.cart': 'Shporta',
    
    // Common
    'common.loading': 'Duke ngarkuar...',
    'common.error': 'Gabim',
    'common.success': 'Sukses',
    'common.failed': 'Dështoi',
    'common.required': 'E detyrueshme',
    'common.optional': 'Opsionale',
    'common.save': 'Ruaj',
    'common.cancel': 'Anulo',
    'common.delete': 'Fshi',
    'common.edit': 'Ndrysho',
    'common.close': 'Mbyll',
    'common.back': 'Mbrapa',
    'common.next': 'Tjetra',
    'common.previous': 'E mëparshme',
    'common.submit': 'Dërgo',
    'common.reset': 'Rivendos',
    'common.search': 'Kërko',
    'common.filter': 'Filtro',
    'common.view': 'Shiko',
    'common.details': 'Detajet',
    'common.settings': 'Cilësimet',
    'common.yes': 'Po',
    'common.no': 'Jo',
    'common.confirm': 'Konfirmo',
    'common.select': 'Zgjidh',
    'common.choose': 'Zgjidh',
    'common.remove': 'Hiq',
    'common.clear': 'Pastro',
    'common.upload': 'Ngarko',
    'common.download': 'Shkarko',
    'common.processing': 'Duke përpunuar...',
    'common.processingVideo': 'Duke përpunuar...',
    'common.processExportVideo': 'Përpunoni & Eksportoni Video',
    // Extras for homepage/profile
    'common.free': 'Falas',
    'index.viewHours': 'Shiko Orët',
    'index.noPrograms': 'Aktualisht nuk ka programe trajnimi të disponueshme.',
    'index.starts': 'Fillon',
    'index.ends': 'Mbaron',
    'index.about.p1': 'Te Fitness Practica, besojmë se fitnesi është më shumë se thjesht ushtrime—është një stil jete. Fushat tona moderne janë të pajisura me pajisje trajnimi të fundit, trajnerë ekspertë dhe një komunitet mbështetës për t\'ju ndihmuar të arrini performancën tuaj maksimale.',
    'index.about.p2': 'Qoftë fillestar në udhëtimin tuaj të fitnesit apo atlet me përvojë që shtyn kufijtë, ne ofrojmë programe të personalizuara trajnimi, klasa në grup dhe udhëzime ushqyese të përshtatura për qëllimet tuaja unike.',
    'profile.purchased': 'Blerë',
    'profile.expires': 'Skadon',
    'profile.openMedia': 'Hap median e bashkëngjitur',
    'profile.viewDetails': 'Shiko detajet e programit',
    'profile.unknownProgram': 'Program i Panjohur',
    'profile.programDates': 'Datat e Programit',
    'profile.noVideos': 'Ende nuk ka video të bashkëngjitura për këtë program.',
    'profile.continue': 'Vazhdo',
    'profile.changePassword': 'Ndrysho Fjalëkalimin',
    'profile.currentPassword': 'Fjalëkalimi Aktual',
    'profile.newPassword': 'Fjalëkalimi i Ri',
    'profile.confirmNewPassword': 'Konfirmo Fjalëkalimin e Ri',
    'profile.currentPasswordPlaceholder': 'Shkruani fjalëkalimin aktual',
    'profile.newPasswordPlaceholder': 'Shkruani fjalëkalimin e ri',
    'profile.confirmNewPasswordPlaceholder': 'Konfirmoni fjalëkalimin e ri',
    'profile.passwordUpdated': 'Fjalëkalimi u përditësua me sukses!',
    'profile.passwordUpdateFailed': 'Dështoi përditësimi i fjalëkalimit',
    'profile.passwordsNotMatch': 'Fjalëkalimet e reja nuk përputhen',
    'profile.passwordTooShort': 'Fjalëkalimi duhet të jetë të paktën 6 karaktere',
    'profile.currentPasswordRequired': 'Fjalëkalimi aktual është i detyrueshëm',
    'profile.changeEmail': 'Ndrysho Email',
    'profile.newEmail': 'Email i Ri',
    'profile.newEmailPlaceholder': 'Shkruani email-in e ri',
    'profile.emailUpdated': 'Email-i u përditësua me sukses!',
    'profile.emailUpdateFailed': 'Dështoi përditësimi i email-it',
    'profile.emailAlreadyExists': 'Email-i është në përdorim',
    'profile.invalidEmail': 'Format email-i i pavlefshëm',
    
    // About Us
    'about.title': 'Rreth Nesh',
    'about.subtitle': 'Partneri juaj i besuar në fitnes dhe mirëqenie',
    'about.mission.title': 'Misioni Ynë',
    'about.mission.description': 'Në Fitness Practica, jemi të përkushtuar për të ndihmuar individët të arrijnë qëllimet e tyre të fitnesit përmes programeve të personalizuara të trajnimit, udhëzimeve eksperte dhe një komuniteti mbështetës. Ne besojmë se çdokush meriton qasje në burime cilësore të fitnesit që mund të transformojnë jetën e tyre.',
    'about.values.title': 'Vlerat Tona',
    'about.values.excellence.title': 'Ekselenca',
    'about.values.excellence.description': 'Ne përpiqemi për ekselencë në çdo program që ofrojmë, duke siguruar përvojat më cilësore të trajnimit.',
    'about.values.community.title': 'Komuniteti',
    'about.values.community.description': 'Ne ndërtojmë një komunitet mbështetës ku anëtarët mund të ndajnë udhëtimin e tyre dhe të motivojnë njëri-tjetrin.',
    'about.values.dedication.title': 'Përkushtimi',
    'about.values.dedication.description': 'Jemi të përkushtuar për suksesin tuaj dhe të dedikuar për t\'ju ndihmuar të arrini qëllimet tuaja të fitnesit.',
    'about.values.quality.title': 'Cilësia',
    'about.values.quality.description': 'Çdo program është krijuar me kujdes nga ekspertët e fitnesit për të siguruar rezultatet më të mira.',
    'about.values.progress.title': 'Progresi',
    'about.values.progress.description': 'Ne gjurmojmë dhe festojmë progresin tuaj, duke ju ndihmuar të qëndroni të motivuar dhe të arrini përmirësim të vazhdueshëm.',
    'about.story.title': 'Historia Jonë',
    'about.story.paragraph1': 'Fitness Practica u themelua me një vizion të thjeshtë por të fuqishëm: të bëjë trajnimin profesional të fitnesit të arritshëm për të gjithë. Ne kuptojmë se udhëtimi i fitnesit i çdo personi është unik, dhe ne jemi këtu për të ofruar mjetet, udhëzimet dhe mbështetjen e nevojshme për sukses.',
    'about.story.paragraph2': 'Ekipi ynë i trajnerëve me përvojë dhe ekspertëve të fitnesit punon pa u lodhur për të krijuar programe gjithëpërfshirëse që përmbushin nivele dhe qëllime të ndryshme fitnesi. Pavarësisht nëse po kërkoni të humbni peshë, të ndërtoni muskuj, të përmirësoni fleksibilitetin, ose të përmirësoni shëndetin tuaj të përgjithshëm, ne kemi një program të dizajnuar për ju.',
    'about.story.paragraph3': 'Bashkohuni me mijëra anëtarë të kënaqur që kanë transformuar jetën e tyre përmes programeve tona. Udhëtimi juaj i fitnesit fillon këtu, dhe ne jemi të ngazëllyer të jemi pjesë e tij.',
    'about.box1.title': 'Përkushtimi Ynë',
    'about.box1.description': '<p style="margin-bottom: 1rem;">🔹 <strong>Pozicioni:</strong> Instruktor Fitnesi, Aerobie, Pilates, Tabata Insanity</p><p style="margin-bottom: 1rem;">🔹 <strong>Eksperiencë:</strong> Mbi 25 vite në fushën e aktivitetit fizik</p><p style="margin-bottom: 0.5rem;">🔹 <strong>Specializimet:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Fitnes funksional</li><li style="margin-bottom: 0.25rem;">▪ Trajnim aerobik, pilates, Tabata Insanity, Full Body workout</li><li style="margin-bottom: 0.25rem;">▪ Kondicion fizik për të gjitha moshat</li><li style="margin-bottom: 0.25rem;">▪ Përgatitës Atletik dhe fizik</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Stili i trajnimit:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ I strukturuar, i qartë dhe motivues</li><li style="margin-bottom: 0.25rem;">▪ I përshtatur për të gjitha nivelet – nga fillestarët te të avancuarit</li><li style="margin-bottom: 0.25rem;">▪ Fokus te teknika e saktë dhe progresi gradual</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Përparësitë e punës me të:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Eksperiencë e thellë dhe e provuar në 25 vite</li><li style="margin-bottom: 0.25rem;">▪ Qasje pozitive dhe energji frymëzuese</li><li style="margin-bottom: 0.25rem;">▪ Vëmendje individuale për çdo klient</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Misioni i tij:</strong></p><p style="padding-left: 1.5rem; margin-bottom: 1rem;">Të ndihmojë çdo individ të arrijë potencialin maksimal – fizikisht dhe mendërisht.</p><p style="margin-bottom: 0.5rem;">🔹 <strong>Motto:</strong></p><p style="padding-left: 1.5rem; margin-bottom: 0;">"Disiplina ndërton trupin, përkushtimi forcon karakterin."</p>',
    'about.box2.title': 'Suksesi Juaj',
    'about.box2.description': '<p style="margin-bottom: 1rem;">🔹 <strong>Pozicioni:</strong> Instruktor Fitnesi & Pilates</p><p style="margin-bottom: 1rem;">🔹 <strong>Eksperiencë:</strong> 8 vite në fushën e trajnimit personal dhe grupor</p><p style="margin-bottom: 0.5rem;">🔹 <strong>Specializimet:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Fitnes funksional dhe forcë</li><li style="margin-bottom: 0.25rem;">▪ Pilates për qëndrueshmëri, fleksibilitet dhe balancë</li><li style="margin-bottom: 0.25rem;">▪ Trajnime për tonifikim dhe performancë fizike</li><li style="margin-bottom: 0.25rem;">▪ Përgatitës Atletik dhe fizik</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Stili i trajnimit:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Dinamik, bashkëkohor dhe i përshtatur sipas nevojave individuale</li><li style="margin-bottom: 0.25rem;">▪ Kombinon teknikat moderne të Pilates me principet bazë të fitnesit</li><li style="margin-bottom: 0.25rem;">▪ Fokus te lidhja trup-mendje dhe progresi afatgjatë</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Përparësitë e punës me të:</strong></p><ul style="list-style: none; padding-left: 1.5rem; margin-bottom: 1rem;"><li style="margin-bottom: 0.25rem;">▪ Qasje profesionale dhe miqësore</li><li style="margin-bottom: 0.25rem;">▪ Seanca të organizuara dhe efektive</li><li style="margin-bottom: 0.25rem;">▪ Mbështetje e vazhdueshme për motivim dhe përmirësim</li></ul><p style="margin-bottom: 0.5rem;">🔹 <strong>Misioni i tij:</strong></p><p style="padding-left: 1.5rem; margin-bottom: 1rem;">Të ndihmojë çdo klient të ndjehet më i fortë, më i qëndrueshëm dhe më i sigurt në trupin e vet.</p><p style="margin-bottom: 0.5rem;">🔹 <strong>Motto:</strong></p><p style="padding-left: 1.5rem; margin-bottom: 0;">"Trupi është mjeti yt – mëso ta përdorësh me kontroll dhe vetëdije."</p>',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

