import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'al';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.login': 'Login',
    'header.signup': 'Sign Up',
    'header.logout': 'Logout',
    'header.profile': 'Profile',
    
    // Hero
    'hero.title': 'Fitness Practica',
    'hero.subtitle': 'Transform your body, elevate your mind, achieve your goals',
    'hero.button': 'Start Your Journey',
    
    // Sections
    'section.plans.title': 'Choose Your Plan',
    'section.plans.subtitle': 'Find the perfect fit for your fitness journey',
    'section.programs.title': 'Training Programs',
    'section.programs.subtitle': 'Specialized programs designed for your goals',
    'section.about.title': 'Your Fitness',
    'section.about.title2': 'Transformation',
    'section.locations.title': 'Our Locations',
    'section.locations.subtitle': 'Find us at one of our convenient locations',
    
    // Footer
    'footer.tagline': 'Transform your life through fitness',
    'footer.contact': 'Contact Us',
    'footer.hours': 'Hours',
    'footer.hours.weekdays': 'Monday - Friday: 5:00 AM - 11:00 PM',
    'footer.hours.weekend': 'Saturday - Sunday: 7:00 AM - 9:00 PM',
    'footer.copyright': '© 2024 Fitness Practica. All rights reserved.',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.empty': 'Your cart is empty',
    'checkout.emptyMessage': 'Add some programs to your cart to get started!',
    'checkout.program': 'Program',
    'checkout.category': 'Category',
    'checkout.remove': 'Remove',
    'checkout.total': 'Total',
    'checkout.programs': 'programs',
    'checkout.completeOrder': 'Complete Order',
    'checkout.backToPrograms': 'Back to Programs',
    
    // Buttons
    'button.learnMore': 'Learn More',
    'button.browsePrograms': 'Browse Programs',
    'button.loginToPurchase': 'Log in to purchase',
    'button.continue': 'Continue',
    'button.addToCart': 'Add to Cart',
    
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.emailPlaceholder': 'Enter your email',
    'login.passwordPlaceholder': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up',
    'login.failed': 'Login failed. Please try again.',
    
    // Signup
    'signup.title': 'Create Account',
    'signup.subtitle': 'Join us and start your fitness journey',
    'signup.name': 'Full Name',
    'signup.email': 'Email',
    'signup.password': 'Password',
    'signup.confirmPassword': 'Confirm Password',
    'signup.namePlaceholder': 'Enter your full name',
    'signup.emailPlaceholder': 'Enter your email',
    'signup.passwordPlaceholder': 'Create a password',
    'signup.confirmPasswordPlaceholder': 'Confirm your password',
    'signup.createAccount': 'Sign Up',
    'signup.creating': 'Creating account...',
    'signup.hasAccount': 'Already have an account?',
    'signup.signIn': 'Sign in',
    'signup.passwordsNotMatch': 'Passwords do not match',
    'signup.passwordTooShort': 'Password must be at least 6 characters',
    'signup.failed': 'Signup failed. Please try again.',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your account and view your purchased programs',
    'profile.information': 'Profile Information',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.role': 'Role',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.myPrograms': 'My Programs',
    'profile.noPrograms': 'No programs purchased yet',
    'profile.programStatus': 'Status',
    'profile.programStatusActive': 'Active',
    'profile.programStatusFinished': 'Finished',
    'profile.programStatusUpcoming': 'Not Available Yet',
    'profile.programDescription': 'Description',
    'profile.programNoDescription': 'No description available',
    'profile.videoStatus': 'Status',
    'profile.videoNotStarted': 'Not Started',
    'profile.videoInProgress': 'In Progress',
    'profile.videoCompleted': 'Completed',
    'profile.videoLocked': 'Locked - Complete previous video',
    'profile.memberSince': 'Member Since',
    'profile.startProgram': 'Start Program',
    
    // Checkout
    'checkout.proceedToPayment': 'Proceed to Payment',
    'checkout.processing': 'Processing...',
    'checkout.paymentSuccess': 'Payment successful! Redirecting to profile...',
    'checkout.paymentFailed': 'Payment failed or was canceled. Please try again.',
    'checkout.program': 'program',
    'checkout.programs': 'programs',
    'checkout.noValidPrograms': 'No valid programs in cart',
    'checkout.failedToCreateSession': 'Failed to create checkout session',
    'checkout.failedToProcess': 'Failed to process payment',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.loading': 'Loading dashboard...',
    'admin.accessDenied': 'Access denied. Admin privileges required.',
    'admin.stats': 'Statistics',
    'admin.users': 'Users',
    'admin.transactions': 'Transactions',
    'admin.programs': 'Programs',
    'admin.addUser': 'Add User',
    'admin.addProgram': 'Add Program',
    'admin.totalUsers': 'Total Users',
    'admin.totalTransactions': 'Total Transactions',
    'admin.totalRevenue': 'Total Revenue',
    'admin.recentTransactions': 'Recent Transactions (30 days)',
    'admin.noUsers': 'No users found',
    'admin.noTransactions': 'No transactions found',
    'admin.noPrograms': 'No programs found',
    'admin.id': 'ID',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.phone': 'Phone',
    'admin.role': 'Role',
    'admin.payments': 'Payments',
    'admin.created': 'Created',
    'admin.userName': 'User Name',
    'admin.userEmail': 'User Email',
    'admin.itemName': 'Item Name',
    'admin.itemType': 'Item Type',
    'admin.amount': 'Amount',
    'admin.status': 'Status',
    'admin.date': 'Date',
    'admin.category': 'Category',
    'admin.description': 'Description',
    'admin.price': 'Price',
    'admin.startDate': 'Start Date',
    'admin.endDate': 'End Date',
    'admin.imageUrl': 'Image URL',
    'admin.actions': 'Actions',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.editProgram': 'Edit Program',
    'admin.deleteProgram': 'Delete Program',
    'admin.viewImage': 'View Image',
    'admin.free': 'Free',
    'admin.na': 'N/A',
    'admin.createUserTitle': 'Create New User',
    'admin.nameRequired': 'Name *',
    'admin.emailRequired': 'Email *',
    'admin.passwordRequired': 'Password *',
    'admin.creating': 'Creating...',
    'admin.createUser': 'Create User',
    'admin.userCreated': 'User created successfully!',
    'admin.failedToCreateUser': 'Failed to create user',
    'admin.emailPasswordNameRequired': 'Email, password, and name are required',
    'admin.createProgramTitle': 'Create New Training Program',
    'admin.editProgramTitle': 'Edit Training Program',
    'admin.programName': 'Program Name',
    'admin.programCategory': 'Category',
    'admin.programDescription': 'Description',
    'admin.programImage': 'Program Image',
    'admin.programPrice': 'Price (ALL)',
    'admin.programStartDate': 'Start Date',
    'admin.programEndDate': 'End Date',
    'admin.programNamePlaceholder': 'e.g., Fat Burn Program',
    'admin.programCategoryPlaceholder': 'e.g., Weight Loss, Muscle Growth',
    'admin.programDescriptionPlaceholder': 'Program description...',
    'admin.programPricePlaceholder': '49.99',
    'admin.next': 'Next',
    'admin.back': 'Back',
    'admin.uploadVideo': 'Upload Video',
    'admin.selectExistingVideo': 'Select Existing Video',
    'admin.nameCategoryRequired': 'Name and category are required',
    'admin.programCreated': 'Program created successfully!',
    'admin.programUpdated': 'Program updated successfully!',
    'admin.programDeleted': 'Program deleted successfully!',
    'admin.failedToCreateProgram': 'Failed to create program',
    'admin.failedToUpdateProgram': 'Failed to update program',
    'admin.failedToDeleteProgram': 'Failed to delete program',
    'admin.failedToLoadProgram': 'Failed to load program',
    'admin.failedToLoadDetails': 'Failed to load program details',
    'admin.noProgramSelected': 'No program selected for editing',
    'admin.failedToUploadImage': 'Failed to upload image',
    'admin.programCreatedVideoFailed': 'Program created but video attachment failed. You can attach it later.',
    'admin.deleteConfirm': 'Are you sure you want to delete this program? This will also delete all associated videos. This action cannot be undone.',
    'admin.updating': 'Updating...',
    'admin.updateProgram': 'Update Program',
    'admin.videoUpdated': 'Video updated successfully with new exercises!',
    'admin.videoProcessedUpdateFailed': 'Video processed but update failed. Please try updating the program.',
    'admin.processingFinishedUnexpected': 'Processing finished but server returned unexpected JSON.',
    'admin.errorConnecting': 'Error connecting to server.',
    'admin.uploadVideoOrSelect': 'Please upload a video or select an existing video first!',
    'admin.markExercise': 'Please mark at least one exercise first!',
    'admin.addExerciseOrOverlay': 'Please add at least one exercise or overlay.',
    'admin.authTokenNotFound': 'Authentication token not found. Please log in again.',
    'admin.switchLanguage': 'Switch to Albanian',
    'admin.switchToEnglish': 'Kalo në Anglisht',
    'admin.cart': 'Cart',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.failed': 'Failed',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.view': 'View',
    'common.details': 'Details',
    'common.settings': 'Settings',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.select': 'Select',
    'common.choose': 'Choose',
    'common.remove': 'Remove',
    'common.clear': 'Clear',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.processing': 'Processing...',
    'common.processingVideo': 'Processing...',
    'common.processExportVideo': 'Process & Export Video',
  },
  al: {
    // Header
    'header.login': 'Hyr',
    'header.signup': 'Regjistrohu',
    'header.logout': 'Dil',
    'header.profile': 'Profili',
    
    // Hero
    'hero.title': 'Fitness Practica',
    'hero.subtitle': 'Transformo trupin, ngritë mendjen, arritë qëllimet',
    'hero.button': 'Fillo Udhëtimin Tënd',
    
    // Sections
    'section.plans.title': 'Zgjidh Planin Tënd',
    'section.plans.subtitle': 'Gjej përshtatjen e përsosur për udhëtimin tënd të fitnesit',
    'section.programs.title': 'Programe Trajnimi',
    'section.programs.subtitle': 'Programe të specializuara të dizajnuara për qëllimet e tua',
    'section.about.title': 'Transformimi',
    'section.about.title2': 'i Fitnesit Tënd',
    'section.locations.title': 'Lokacionet Tona',
    'section.locations.subtitle': 'Na gjej në një nga lokacionet tona të përshtatshme',
    
    // Footer
    'footer.tagline': 'Transformo jetën përmes fitnesit',
    'footer.contact': 'Kontakto',
    'footer.hours': 'Orët',
    'footer.hours.weekdays': 'E Hënë - E Premte: 5:00 - 23:00',
    'footer.hours.weekend': 'E Shtunë - E Dielë: 7:00 - 21:00',
    'footer.copyright': '© 2024 Fitness Practica. Të gjitha të drejtat e rezervuara.',
    
    // Checkout
    'checkout.title': 'Blerje',
    'checkout.empty': 'Shporta juaj është e zbrazët',
    'checkout.emptyMessage': 'Shtoni disa programe në shportën tuaj për të filluar!',
    'checkout.program': 'Programi',
    'checkout.category': 'Kategoria',
    'checkout.remove': 'Hiq',
    'checkout.total': 'Totali',
    'checkout.programs': 'programe',
    'checkout.completeOrder': 'Përfundo Porosinë',
    'checkout.backToPrograms': 'Kthehu te Programet',
    
    // Buttons
    'button.learnMore': 'Më Shumë',
    'button.browsePrograms': 'Shfleto Programet',
    'button.loginToPurchase': 'Hyr për të blerë',
    'button.continue': 'Vazhdo',
    'button.addToCart': 'Shto në Shportë',
    
    // Login
    'login.title': 'Mirë Se Vini',
    'login.subtitle': 'Hyni në llogarinë tuaj',
    'login.email': 'Email',
    'login.password': 'Fjalëkalimi',
    'login.emailPlaceholder': 'Shkruani email-in tuaj',
    'login.passwordPlaceholder': 'Shkruani fjalëkalimin tuaj',
    'login.signIn': 'Hyr',
    'login.signingIn': 'Duke hyrë...',
    'login.noAccount': 'Nuk keni llogari?',
    'login.signUp': 'Regjistrohu',
    'login.failed': 'Hyrja dështoi. Ju lutemi provoni përsëri.',
    
    // Signup
    'signup.title': 'Krijo Llogari',
    'signup.subtitle': 'Bashkohuni me ne dhe filloni udhëtimin tuaj të fitnesit',
    'signup.name': 'Emri i Plotë',
    'signup.email': 'Email',
    'signup.password': 'Fjalëkalimi',
    'signup.confirmPassword': 'Konfirmo Fjalëkalimin',
    'signup.namePlaceholder': 'Shkruani emrin tuaj të plotë',
    'signup.emailPlaceholder': 'Shkruani email-in tuaj',
    'signup.passwordPlaceholder': 'Krijoni një fjalëkalim',
    'signup.confirmPasswordPlaceholder': 'Konfirmoni fjalëkalimin tuaj',
    'signup.createAccount': 'Regjistrohu',
    'signup.creating': 'Duke krijuar llogarinë...',
    'signup.hasAccount': 'Keni tashmë një llogari?',
    'signup.signIn': 'Hyr',
    'signup.passwordsNotMatch': 'Fjalëkalimet nuk përputhen',
    'signup.passwordTooShort': 'Fjalëkalimi duhet të jetë të paktën 6 karaktere',
    'signup.failed': 'Regjistrimi dështoi. Ju lutemi provoni përsëri.',
    
    // Profile
    'profile.title': 'Profili Im',
    'profile.subtitle': 'Menaxhoni llogarinë tuaj dhe shikoni programet e blera',
    'profile.information': 'Informacioni i Profilit',
    'profile.name': 'Emri',
    'profile.email': 'Email',
    'profile.phone': 'Telefoni',
    'profile.role': 'Roli',
    'profile.save': 'Ruaj',
    'profile.cancel': 'Anulo',
    'profile.myPrograms': 'Programet e Mia',
    'profile.noPrograms': 'Nuk keni blerë programe ende',
    'profile.programStatus': 'Statusi',
    'profile.programStatusActive': 'Aktiv',
    'profile.programStatusFinished': 'Përfunduar',
    'profile.programStatusUpcoming': 'Ende Nuk Është i Disponueshëm',
    'profile.programDescription': 'Përshkrimi',
    'profile.programNoDescription': 'Nuk ka përshkrim të disponueshëm',
    'profile.videoStatus': 'Statusi',
    'profile.videoNotStarted': 'Nuk Është Filluar',
    'profile.videoInProgress': 'Në Progres',
    'profile.videoCompleted': 'Përfunduar',
    'profile.videoLocked': 'E Kyçur - Përfundoni videon e mëparshme',
    'profile.memberSince': 'Anëtar Që',
    'profile.startProgram': 'Fillo Programin',
    
    // Checkout
    'checkout.proceedToPayment': 'Vazhdo te Pagesa',
    'checkout.processing': 'Duke përpunuar...',
    'checkout.paymentSuccess': 'Pagesa u krye me sukses! Po ridrejtohet te profili...',
    'checkout.paymentFailed': 'Pagesa dështoi ose u anulua. Ju lutemi provoni përsëri.',
    'checkout.program': 'program',
    'checkout.programs': 'programe',
    'checkout.noValidPrograms': 'Nuk ka programe të vlefshme në shportë',
    'checkout.failedToCreateSession': 'Dështoi krijimi i sesionit të blerjes',
    'checkout.failedToProcess': 'Dështoi përpunimi i pagesës',
    
    // Admin Dashboard
    'admin.dashboard': 'Paneli i Administratorit',
    'admin.loading': 'Duke ngarkuar panelin...',
    'admin.accessDenied': 'Qasja u refuzua. Kërkohen privilegje administratori.',
    'admin.stats': 'Statistikat',
    'admin.users': 'Përdoruesit',
    'admin.transactions': 'Transaksionet',
    'admin.programs': 'Programet',
    'admin.addUser': 'Shto Përdorues',
    'admin.addProgram': 'Shto Program',
    'admin.totalUsers': 'Totali i Përdoruesve',
    'admin.totalTransactions': 'Totali i Transaksioneve',
    'admin.totalRevenue': 'Të Ardhurat Totale',
    'admin.recentTransactions': 'Transaksionet e Fundit (30 ditë)',
    'admin.noUsers': 'Nuk u gjetën përdorues',
    'admin.noTransactions': 'Nuk u gjetën transaksione',
    'admin.noPrograms': 'Nuk u gjetën programe',
    'admin.id': 'ID',
    'admin.name': 'Emri',
    'admin.email': 'Email',
    'admin.phone': 'Telefoni',
    'admin.role': 'Roli',
    'admin.payments': 'Pagesat',
    'admin.created': 'Krijuar',
    'admin.userName': 'Emri i Përdoruesit',
    'admin.userEmail': 'Email i Përdoruesit',
    'admin.itemName': 'Emri i Artikullit',
    'admin.itemType': 'Lloji i Artikullit',
    'admin.amount': 'Shuma',
    'admin.status': 'Statusi',
    'admin.date': 'Data',
    'admin.category': 'Kategoria',
    'admin.description': 'Përshkrimi',
    'admin.price': 'Çmimi',
    'admin.startDate': 'Data e Fillimit',
    'admin.endDate': 'Data e Mbarimit',
    'admin.imageUrl': 'URL e Imazhit',
    'admin.actions': 'Veprimet',
    'admin.edit': 'Ndrysho',
    'admin.delete': 'Fshi',
    'admin.editProgram': 'Ndrysho Programin',
    'admin.deleteProgram': 'Fshi Programin',
    'admin.viewImage': 'Shiko Imazhin',
    'admin.free': 'Falas',
    'admin.na': 'N/A',
    'admin.createUserTitle': 'Krijo Përdorues të Ri',
    'admin.nameRequired': 'Emri *',
    'admin.emailRequired': 'Email *',
    'admin.passwordRequired': 'Fjalëkalimi *',
    'admin.creating': 'Duke krijuar...',
    'admin.createUser': 'Krijo Përdorues',
    'admin.userCreated': 'Përdoruesi u krijua me sukses!',
    'admin.failedToCreateUser': 'Dështoi krijimi i përdoruesit',
    'admin.emailPasswordNameRequired': 'Email, fjalëkalimi dhe emri janë të detyrueshëm',
    'admin.createProgram': 'Krijo Program Trajnimi të Ri',
    'admin.createProgramTitle': 'Krijo Program Trajnimi të Ri',
    'admin.editProgramTitle': 'Ndrysho Program Trajnimi',
    'admin.programName': 'Emri i Programit',
    'admin.programCategory': 'Kategoria',
    'admin.programDescription': 'Përshkrimi',
    'admin.programImage': 'Imazhi i Programit',
    'admin.programPrice': 'Çmimi (ALL)',
    'admin.programStartDate': 'Data e Fillimit',
    'admin.programEndDate': 'Data e Mbarimit',
    'admin.programNamePlaceholder': 'p.sh., Program Djegie Yndyri',
    'admin.programCategoryPlaceholder': 'p.sh., Humbje Peshe, Rritje Muskujsh',
    'admin.programDescriptionPlaceholder': 'Përshkrimi i programit...',
    'admin.programPricePlaceholder': '49.99',
    'admin.next': 'Tjetra',
    'admin.back': 'Mbrapa',
    'admin.uploadVideo': 'Ngarko Video',
    'admin.selectExistingVideo': 'Zgjidh Video Ekzistuese',
    'admin.nameCategoryRequired': 'Emri dhe kategoria janë të detyrueshëm',
    'admin.programCreated': 'Programi u krijua me sukses!',
    'admin.programUpdated': 'Programi u përditësua me sukses!',
    'admin.programDeleted': 'Programi u fshi me sukses!',
    'admin.failedToCreateProgram': 'Dështoi krijimi i programit',
    'admin.failedToUpdateProgram': 'Dështoi përditësimi i programit',
    'admin.failedToDeleteProgram': 'Dështoi fshirja e programit',
    'admin.failedToLoadProgram': 'Dështoi ngarkimi i programit',
    'admin.failedToLoadDetails': 'Dështoi ngarkimi i detajeve të programit',
    'admin.noProgramSelected': 'Nuk është zgjedhur program për ndryshim',
    'admin.failedToUploadImage': 'Dështoi ngarkimi i imazhit',
    'admin.programCreatedVideoFailed': 'Programi u krijua por lidhja e videos dështoi. Mund ta lidhni më vonë.',
    'admin.deleteConfirm': 'Jeni të sigurt që dëshironi të fshini këtë program? Kjo do të fshijë edhe të gjitha videot e lidhura. Ky veprim nuk mund të zhbëhet.',
    'admin.updating': 'Duke përditësuar...',
    'admin.updateProgram': 'Përditëso Programin',
    'admin.videoUpdated': 'Videoja u përditësua me sukses me ushtrime të reja!',
    'admin.videoProcessedUpdateFailed': 'Videoja u përpunua por përditësimi dështoi. Ju lutemi provoni të përditësoni programin.',
    'admin.processingFinishedUnexpected': 'Përpunimi përfundoi por serveri ktheu JSON të papritur.',
    'admin.errorConnecting': 'Gabim në lidhje me serverin.',
    'admin.uploadVideoOrSelect': 'Ju lutemi ngarkoni një video ose zgjidhni një video ekzistuese!',
    'admin.markExercise': 'Ju lutemi shënoni të paktën një ushtrim fillimisht!',
    'admin.addExerciseOrOverlay': 'Ju lutemi shtoni të paktën një ushtrim ose mbivendosje.',
    'admin.authTokenNotFound': 'Tokeni i autentifikimit nuk u gjet. Ju lutemi hyni përsëri.',
    'admin.switchLanguage': 'Kalo në Shqip',
    'admin.switchToEnglish': 'Switch to English',
    'admin.cart': 'Shporta',
    'admin.member': 'Anëtar',
    'admin.admin': 'Administrator',
    'admin.member': 'Member',
    'admin.admin': 'Admin',
    
    // Common
    'common.loading': 'Duke ngarkuar...',
    'common.error': 'Gabim',
    'common.success': 'Sukses',
    'common.failed': 'Dështoi',
    'common.required': 'E detyrueshme',
    'common.optional': 'Opsionale',
    'common.save': 'Ruaj',
    'common.cancel': 'Anulo',
    'common.delete': 'Fshi',
    'common.edit': 'Ndrysho',
    'common.close': 'Mbyll',
    'common.back': 'Mbrapa',
    'common.next': 'Tjetra',
    'common.previous': 'E mëparshme',
    'common.submit': 'Dërgo',
    'common.reset': 'Rivendos',
    'common.search': 'Kërko',
    'common.filter': 'Filtro',
    'common.view': 'Shiko',
    'common.details': 'Detajet',
    'common.settings': 'Cilësimet',
    'common.yes': 'Po',
    'common.no': 'Jo',
    'common.confirm': 'Konfirmo',
    'common.select': 'Zgjidh',
    'common.choose': 'Zgjidh',
    'common.remove': 'Hiq',
    'common.clear': 'Pastro',
    'common.upload': 'Ngarko',
    'common.download': 'Shkarko',
    'common.processing': 'Duke përpunuar...',
    'common.processingVideo': 'Duke përpunuar...',
    'common.processExportVideo': 'Përpunoni & Eksportoni Video',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

